# Created a similar excel file with the columns "OrderDate" and "salesMan"

In [52]:
# Let's first read the Excel file using pandas to see what it contains
import pandas as pd

# Load a sheet into a DataFrame
df = pd.read_excel('sales_data.xlsx')

df.head(20)  # display the first few rows of the dataframe

,SalesMan,OrderDate,Product,Quantity,UnitPrice,TotalSales
0,NaN,30/05/22,Mobile Phone,33,125.386412,4137.751585
1,Amanda Preston,16/07/22,TV,79,92.829962,7333.566960
2,Tiffany Ward,18/09/22,Mouse,11,184.148653,2025.635178
3,Jennifer Ferguson,06/12/22,Mouse,89,37.295687,3319.316180
4,NaN,20/10/22,Camera,10,95.616888,956.168881
5,Natalie Dyer,29/05/22,Headphones,80,44.269048,3541.523830
6,Rebecca Robinson,01/03/22,Monitor,15,183.261718,2748.925776
7,Mary Blackburn,23/07/22,Laptop,36,70.573977,2540.663171
8,Richard Davis,13/06/22,TV,60,198.420515,11905.230889
9,James Benjamin,05/09/22,Mobile Phone,64,181.838025,11637.633604
10,Amber Sanchez,14/10/22,Camera,16,143.925390,2302.806239
11,NaN,24/08/22,Headphones,14,78.210836,1094.951702
12,Joshua Vasquez,20/08/22,Mobile Phone,20,67.757797,1355.155941
13,Thomas Howell,08/05/22,TV,30,184.819471,5544.584118
14,Ashley Williams,21/05/22,Laptop,74,33.607505,2486.955348
15,Ernest Blake,01/03/22,Headphones,32,100.423029,3213.536939
16,Stacey Lewis,08/10/22,Camera,48,199.317842,9567.256393
17,NaN,22/11/22,Keyboard,55,171.741869,9445.802795
18,Stacey Hodge,16/04/22,Keyboard,62,105.411946,6535.540653
19,David Cross,18/07/22,Mouse,67,24.894378,1667.923318

### Now, Replacing all empty cells in “SalesMan” column with my Name.

In [53]:
df['SalesMan'].fillna('Kanchan Sharma', inplace=True)
df

,SalesMan,OrderDate,Product,Quantity,UnitPrice,TotalSales
0,Kanchan Sharma,30/05/22,Mobile Phone,33,125.386412,4137.751585
1,Amanda Preston,16/07/22,TV,79,92.829962,7333.566960
2,Tiffany Ward,18/09/22,Mouse,11,184.148653,2025.635178
3,Jennifer Ferguson,06/12/22,Mouse,89,37.295687,3319.316180
4,Kanchan Sharma,20/10/22,Camera,10,95.616888,956.168881
5,Natalie Dyer,29/05/22,Headphones,80,44.269048,3541.523830
6,Rebecca Robinson,01/03/22,Monitor,15,183.261718,2748.925776
7,Mary Blackburn,23/07/22,Laptop,36,70.573977,2540.663171
8,Richard Davis,13/06/22,TV,60,198.420515,11905.230889
9,James Benjamin,05/09/22,Mobile Phone,64,181.838025,11637.633604
10,Amber Sanchez,14/10/22,Camera,16,143.925390,2302.806239
11,Kanchan Sharma,24/08/22,Headphones,14,78.210836,1094.951702
12,Joshua Vasquez,20/08/22,Mobile Phone,20,67.757797,1355.155941
13,Thomas Howell,08/05/22,TV,30,184.819471,5544.584118
14,Ashley Williams,21/05/22,Laptop,74,33.607505,2486.955348
15,Ernest Blake,01/03/22,Headphones,32,100.423029,3213.536939
16,Stacey Lewis,08/10/22,Camera,48,199.317842,9567.256393
17,Kanchan Sharma,22/11/22,Keyboard,55,171.741869,9445.802795
18,Stacey Hodge,16/04/22,Keyboard,62,105.411946,6535.540653
19,David Cross,18/07/22,Mouse,67,24.894378,1667.923318
20,Paul Jordan,21/02/22,TV,16,19.459033,311.344528
21,Randy Henderson,23/01/22,Tablet,5,42.355652,211.778260
22,Kanchan Sharma,20/11/22,TV,1,138.056191,138.056191
23,Terrence Neal,05/09/22,Keyboard,16,29.449055,471.184874
24,Miguel Johnson,31/08/22,TV,97,72.885028,7069.847686
25,Stephanie Schwartz,17/10/22,Laptop,46,65.199507,2999.177338
26,Keith Carter,12/02/22,Printer,1,148.451208,148.451208
27,Kanchan Sharma,20/01/22,Camera,66,193.021766,12739.436550
28,Christine Rivera,26/07/22,Mobile Phone,13,38.163104,496.120352
29,Andrea Hayes,28/01/22,Mobile Phone,54,135.457712,7314.716436
30,Kevin Bailey,25/02/22,Printer,95,13.328055,1266.165264
31,Jordan Watson,03/11/22,Printer,40,154.952763,6198.110538
32,Jennifer Huerta,07/09/22,Camera,61,46.687651,2847.946722
33,Ricky English,17/05/22,Monitor,21,22.943831,481.820444
34,Kanchan Sharma,03/08/22,Monitor,23,155.439707,3575.113250
35,Benjamin Scott,20/10/22,Camera,20,185.258873,3705.177470
36,Kanchan Sharma,18/08/22,Laptop,66,95.347928,6292.963215
37,Joshua Key,19/11/22,Laptop,87,151.827491,13208.991700
38,Carlos Sandoval,09/10/22,Camera,61,142.550553,8695.583749
39,Amy Collins,25/07/22,Headphones,46,44.937801,2067.138834
40,Jessica Callahan,22/02/22,Tablet,34,12.998535,441.950175
41,William Miller,30/12/22,Headphones,40,174.474179,6978.967178
42,Kanchan Sharma,14/06/22,Monitor,97,145.538669,14117.250875
43,Elizabeth Underwood,14/02/22,Printer,34,13.054816,443.863735
44,Kanchan Sharma,12/04/22,Keyboard,28,124.812488,3494.749655
45,Douglas Perry,01/04/22,Keyboard,62,125.900829,7805.851378
46,Duane Miller,07/11/22,Laptop,47,55.387686,2603.221261
47,Dennis Rojas,02/02/22,Tablet,73,145.748491,10639.639830
48,Nicole Warner,03/08/22,Camera,55,97.866987,5382.684262
49,Nancy Peters,26/05/22,TV,55,30.261381,1664.375981

In [57]:
# viewing the dates of OrderDate column
df['OrderDate']

0     30/05/22
1     16/07/22
2     18/09/22
3     06/12/22
4     20/10/22
5     29/05/22
6     01/03/22
7     23/07/22
8     13/06/22
9     05/09/22
10    14/10/22
11    24/08/22
12    20/08/22
13    08/05/22
14    21/05/22
15    01/03/22
16    08/10/22
17    22/11/22
18    16/04/22
19    18/07/22
20    21/02/22
21    23/01/22
22    20/11/22
23    05/09/22
24    31/08/22
25    17/10/22
26    12/02/22
27    20/01/22
28    26/07/22
29    28/01/22
30    25/02/22
31    03/11/22
32    07/09/22
33    17/05/22
34    03/08/22
35    20/10/22
36    18/08/22
37    19/11/22
38    09/10/22
39    25/07/22
40    22/02/22
41    30/12/22
42    14/06/22
43    14/02/22
44    12/04/22
45    01/04/22
46    07/11/22
47    02/02/22
48    03/08/22
49    26/05/22
Name: OrderDate, dtype: object

### Replace all cells in column “OrderDate” with date as “DD/MM/YY” to “DD/MM/20YY”

In [58]:
# (this cell should not be run twice, as it modifies the actual df)

# Convert 'OrderDate' column to datetime
df['OrderDate'] = pd.to_datetime(df['OrderDate'], format='%d/%m/%y')

# Format dates as 'DD/MM/20YY'
df['OrderDate'] = df['OrderDate'].apply(lambda x: x.strftime('%d/%m/20%y'))


df['OrderDate']

0     30/05/2022
1     16/07/2022
2     18/09/2022
3     06/12/2022
4     20/10/2022
5     29/05/2022
6     01/03/2022
7     23/07/2022
8     13/06/2022
9     05/09/2022
10    14/10/2022
11    24/08/2022
12    20/08/2022
13    08/05/2022
14    21/05/2022
15    01/03/2022
16    08/10/2022
17    22/11/2022
18    16/04/2022
19    18/07/2022
20    21/02/2022
21    23/01/2022
22    20/11/2022
23    05/09/2022
24    31/08/2022
25    17/10/2022
26    12/02/2022
27    20/01/2022
28    26/07/2022
29    28/01/2022
30    25/02/2022
31    03/11/2022
32    07/09/2022
33    17/05/2022
34    03/08/2022
35    20/10/2022
36    18/08/2022
37    19/11/2022
38    09/10/2022
39    25/07/2022
40    22/02/2022
41    30/12/2022
42    14/06/2022
43    14/02/2022
44    12/04/2022
45    01/04/2022
46    07/11/2022
47    02/02/2022
48    03/08/2022
49    26/05/2022
Name: OrderDate, dtype: object

In [59]:
# the final dataframe looks like this. With updated names and changing date format 
df

,SalesMan,OrderDate,Product,Quantity,UnitPrice,TotalSales
0,Kanchan Sharma,30/05/2022,Mobile Phone,33,125.386412,4137.751585
1,Amanda Preston,16/07/2022,TV,79,92.829962,7333.566960
2,Tiffany Ward,18/09/2022,Mouse,11,184.148653,2025.635178
3,Jennifer Ferguson,06/12/2022,Mouse,89,37.295687,3319.316180
4,Kanchan Sharma,20/10/2022,Camera,10,95.616888,956.168881
5,Natalie Dyer,29/05/2022,Headphones,80,44.269048,3541.523830
6,Rebecca Robinson,01/03/2022,Monitor,15,183.261718,2748.925776
7,Mary Blackburn,23/07/2022,Laptop,36,70.573977,2540.663171
8,Richard Davis,13/06/2022,TV,60,198.420515,11905.230889
9,James Benjamin,05/09/2022,Mobile Phone,64,181.838025,11637.633604
10,Amber Sanchez,14/10/2022,Camera,16,143.925390,2302.806239
11,Kanchan Sharma,24/08/2022,Headphones,14,78.210836,1094.951702
12,Joshua Vasquez,20/08/2022,Mobile Phone,20,67.757797,1355.155941
13,Thomas Howell,08/05/2022,TV,30,184.819471,5544.584118
14,Ashley Williams,21/05/2022,Laptop,74,33.607505,2486.955348
15,Ernest Blake,01/03/2022,Headphones,32,100.423029,3213.536939
16,Stacey Lewis,08/10/2022,Camera,48,199.317842,9567.256393
17,Kanchan Sharma,22/11/2022,Keyboard,55,171.741869,9445.802795
18,Stacey Hodge,16/04/2022,Keyboard,62,105.411946,6535.540653
19,David Cross,18/07/2022,Mouse,67,24.894378,1667.923318
20,Paul Jordan,21/02/2022,TV,16,19.459033,311.344528
21,Randy Henderson,23/01/2022,Tablet,5,42.355652,211.778260
22,Kanchan Sharma,20/11/2022,TV,1,138.056191,138.056191
23,Terrence Neal,05/09/2022,Keyboard,16,29.449055,471.184874
24,Miguel Johnson,31/08/2022,TV,97,72.885028,7069.847686
25,Stephanie Schwartz,17/10/2022,Laptop,46,65.199507,2999.177338
26,Keith Carter,12/02/2022,Printer,1,148.451208,148.451208
27,Kanchan Sharma,20/01/2022,Camera,66,193.021766,12739.436550
28,Christine Rivera,26/07/2022,Mobile Phone,13,38.163104,496.120352
29,Andrea Hayes,28/01/2022,Mobile Phone,54,135.457712,7314.716436
30,Kevin Bailey,25/02/2022,Printer,95,13.328055,1266.165264
31,Jordan Watson,03/11/2022,Printer,40,154.952763,6198.110538
32,Jennifer Huerta,07/09/2022,Camera,61,46.687651,2847.946722
33,Ricky English,17/05/2022,Monitor,21,22.943831,481.820444
34,Kanchan Sharma,03/08/2022,Monitor,23,155.439707,3575.113250
35,Benjamin Scott,20/10/2022,Camera,20,185.258873,3705.177470
36,Kanchan Sharma,18/08/2022,Laptop,66,95.347928,6292.963215
37,Joshua Key,19/11/2022,Laptop,87,151.827491,13208.991700
38,Carlos Sandoval,09/10/2022,Camera,61,142.550553,8695.583749
39,Amy Collins,25/07/2022,Headphones,46,44.937801,2067.138834
40,Jessica Callahan,22/02/2022,Tablet,34,12.998535,441.950175
41,William Miller,30/12/2022,Headphones,40,174.474179,6978.967178
42,Kanchan Sharma,14/06/2022,Monitor,97,145.538669,14117.250875
43,Elizabeth Underwood,14/02/2022,Printer,34,13.054816,443.863735
44,Kanchan Sharma,12/04/2022,Keyboard,28,124.812488,3494.749655
45,Douglas Perry,01/04/2022,Keyboard,62,125.900829,7805.851378
46,Duane Miller,07/11/2022,Laptop,47,55.387686,2603.221261
47,Dennis Rojas,02/02/2022,Tablet,73,145.748491,10639.639830
48,Nicole Warner,03/08/2022,Camera,55,97.866987,5382.684262
49,Nancy Peters,26/05/2022,TV,55,30.261381,1664.375981